grades:		main.o book.o commands.o
		gcc -o grades main.o book.o commands.o

main.o:		main.c book.h
		gcc -c main.c

book.o:		book.c book.h
		gcc -c book.c

commands.o:	commands.c commands.h
		gcc -c commands.c

clean:
		rm *.o
		rm grades